# https://alacritty.org/config-alacritty.html
[general]
import = ["/Users/ysoftman/.config/alacritty-colorscheme/themes/argonaut.toml"]
#import = ["/Users/ysoftman/.config/alacritty-colorscheme/themes/monokai_charcoal.toml"]
#import = ["/Users/ysoftman/.config/alacritty-colorscheme/themes/marine_dark.toml"]

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.primary]
background = "#000000"
foreground = "#abb2bf"

[colors.footer_bar]
background = "#bbbbbb"
foreground = "#000000"

[colors.search.focused_match]
background = "#c678dd"
foreground = "#000000"

[colors.search.matches]
background = "#f0c674"
foreground = "#000000"

[colors.selection]
background = "#f0c674"
foreground = "#000000"
# text = "CellForeground"

[font]
size = 17.0

[font.bold]
# family = "Hack Nerd Font"
family = "FiraCode Nerd Font"

[font.bold_italic]
# family = "Hack Nerd Font"
family = "FiraCode Nerd Font"

[font.italic]
# family = "Hack Nerd Font"
family = "FiraCode Nerd Font"

[font.normal]
# family = "Hack Nerd Font"
family = "FiraCode Nerd Font"

[cursor]
style.shape = "block"
style.blinking = "off"
vi_mode_style.shape = "block"
vi_mode_style.blinking = "off"

[[keyboard.bindings]]
# \u001b = 0x1b = ESC
# alt+left 왼쭉으로 커서 이동
chars = "\u001Bb"
key = "Left"
mods = "Alt|Option"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt|Option"

[[keyboard.bindings]]
# shift+enter 를 ESC+CR 로 보내 claude code 등에서 다음 줄 입력으로 동작
chars = "\u001B\r"
key = "Enter"
mods = "Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
# action = "None"  # mac에선 cmd+q 가 앱 종료가 None 설정이 의미 없다.
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

# tmux 를 사용하면 alacritty vimode 오버레이를 덮어버려 블럭표시가 tmux 위 표시되지 않는다. prefix(ctrl-b) [ 키로 tmux copy mode 를 사용해야 한다.
[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"

[terminal]

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
option_as_alt = "Both"
opacity = 1
blur = false

[debug]
render_timer = false
log_level = "Warn"
