# https://alacritty.org/config-alacritty.html
[general]
import = ["/Users/ysoftman/.config/alacritty-colorscheme/themes/argonaut.toml"]
#import = ["/Users/ysoftman/.config/alacritty-colorscheme/themes/monokai_charcoal.toml"]
#import = ["/Users/ysoftman/.config/alacritty-colorscheme/themes/marine_dark.toml"]

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.primary]
background = "#000000"
foreground = "#abb2bf"

[colors.footer_bar]
background = "#bbbbbb"
foreground = "#000000"

[colors.search.focused_match]
background = "#c678dd"
foreground = "#000000"

[colors.search.matches]
background = "#f0c674"
foreground = "#000000"

[colors.selection]
background = "#e5c07b"
text = "CellForeground"

[font]
size = 19.0

[font.bold]
family = "Hack Nerd Font"

[font.bold_italic]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[cursor]
style.shape = "block"
style.blinking = "off"
vi_mode_style.shape = "block"
vi_mode_style.blinking = "off"

[[keyboard.bindings]]
# \u001b = 0x1b = ESC
# alt+let 왼쭉으로 커서 이동
chars = "\u001Bb"
key = "Left"
mods = "Alt|Option"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt|Option"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
# action = "None"  # mac에선 cmd+q 가 앱 종료가 None 설정이 의미 없다.
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"

[terminal]

[terminal.shell]
program = "/bin/zsh"

[window]
option_as_alt = "Both"
opacity = 1
blur = false

[debug]
render_timer = false
log_level = "Warn"
