#!/bin/bash
# ysoftman

# backup my vscode settings
mkdir -p vscode_settings
if [[ $(uname -a | grep -i microsoft) ]]; then
    # backup vscode settings
    username=$(wslvar userprofile | tr '\\' ' ' | awk '{print $NF}')
    # 윈도우 wsl 에서 mnt/c 로 마운트되었다고 가정
    # 실제 위치 C:\Users\${username}\AppData\Roaming\Code\User\settings.json
    vscode_setting_path="/mnt/c/Users/${username}/AppData/Roaming/Code/User/"
    cp -v ${vscode_setting_path}/*.json ./vscode_settings/
fi

# backup my brew installed package list and make install script
if which brew; then
    install_file="installbrew.sh"
    {
        echo '#!/bin/bash'
        echo "# auto generated by ${0}"
        # 참고 다음 tap 들은 deprecated 되었다.
        # brew untap homebrew/services
        # brew untap homebrew/cask-fonts
        brew tap | sort | awk '{print "brew tap " $0}'
        printf "brew install "
        brew list | sort | tr '\n' ' ' | awk '{ sub(/[[:space:]]+$/, ""); print }'
    } >${install_file}
fi

# backup my pip installed package list and make install script
if command -v uv >/dev/null 2>&1; then
    PIP="uv pip"
fi
if [[ $PIP != 'NONE' ]]; then
    install_file="installpip.sh"
    pip_list=$(${PIP} list --system | sed -n '3,$p' | awk '{print $1}' | tr '\n' ' ' | awk '{ sub(/[[:space:]]+$/, ""); print }')
    cat <<zzz >${install_file}
#!/bin/bash
# auto generated by ${0}
# pip 가 없을때 설치
# python -m ensurepip --upgrade
# python -m pip install --upgrade pip
PIP="pip"
# uv(extremely fast Python package and project manager)
# https://github.com/astral-sh/uv
if command -v uv >/dev/null 2>&1; then
    PIP="uv pip"
fi
\${PIP} install --upgrade --system pip
\${PIP} install --upgrade --system $pip_list
zzz
fi

# backup my bun globally installed package list and make install script
if command -v bun >/dev/null 2>&1; then
    install_file="installbun.sh"
    bun_list=$(NO_COLOR=1 bun pm ls -g | tail -n +2 | awk '{print $NF}' | sed 's/@[^@]*$//' | sort | tr '\n' ' ' | awk '{ sub(/[[:space:]]+$/, ""); print }')
    {
        echo '#!/bin/bash'
        echo "# auto generated by ${0}"
        echo '# install bun if not installed'
        echo 'command -v bun >/dev/null 2>&1 || curl -fsSL https://bun.com/install | bash'
        echo "bun install -g ${bun_list}"
    } >${install_file}
fi

# 보안사항으로 github 저장소에 올리면 안됨.
# mkdir -p .ssh hosts
# cp -v ~/.ssh/* ./.ssh/
# cp -v /etc/hosts ./hosts

# cron job 백업
crontab -l >cron

echo "cron 파일로 백업되었습니다. cron 잡을 다시 복구하려면 다음 명령으로 기존 cron 잡을 모두 삭제하고 다시 등록하세요."
echo "crontab -r"
echo "crontab cron"

# 커밋되지 민감정보 알림
bash ./scan_gitignored_secrets.sh
