#!/bin/bash

# go install 로 설치된 패키지 모두 업데이트
# gup update
#
# 패키지 목록 파악 설치 커맨드로 변경시
# gup list | awk '{print "go install " $2}' | pbcopy
#
# install tools to $GOPATH/bin
go install github.com/air-verse/air@v1.61.7
go install github.com/klauspost/asmfmt/cmd/asmfmt@v1.3.2
go install golang.org/x/tools/cmd/auth/authtest@v0.32.0
go install golang.org/x/tools/cmd/benchcmp@v0.32.0
go install golang.org/x/tools/cmd/bisect@v0.32.0
go install golang.org/x/tools/cmd/bundle@v0.32.0
go install golang.org/x/tools/cmd/callgraph@v0.32.0
go install golang.org/x/tools/cmd/compilebench@v0.32.0
go install github.com/maaslalani/confetty@v0.0.0-20221105190856-6c6f1b5b605f
go install golang.org/x/tools/cmd/auth/cookieauth@v0.32.0
go install github.com/CondensedMilk7/countryfetch/cmd/countryfetch@v0.0.0-20230516104218-a0e6cc7f0f5d
go install golang.org/x/tools/cmd/deadcode@v0.32.0
go install golang.org/x/tools/go/analysis/passes/defers/cmd/defers@v0.32.0
go install golang.org/x/tools/cmd/digraph@v0.32.0
go install github.com/go-delve/delve/cmd/dlv@v1.24.2
go install golang.org/x/tools/cmd/eg@v0.32.0
go install github.com/kisielk/errcheck@v1.9.0
go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@v0.32.0
go install golang.org/x/tools/cmd/file2fuzz@v0.32.0
go install github.com/davidrjenni/reftools/cmd/fillstruct@v0.0.0-20240211192525-f5f96ef18854
go install github.com/davidrjenni/reftools/cmd/fillswitch@v0.0.0-20240211192525-f5f96ef18854
go install golang.org/x/tools/go/analysis/passes/findcall/cmd/findcall@v0.32.0
go install golang.org/x/tools/cmd/fiximports@v0.32.0
go install github.com/pilu/fresh@v0.0.0-20240621171608-8d1fef547a99
go install golang.org/x/tools/cmd/signature-fuzzer/fuzz-driver@v0.32.0
go install golang.org/x/tools/cmd/signature-fuzzer/fuzz-runner@v0.32.0
go install github.com/onsi/ginkgo/v2/ginkgo@v2.23.4
go install golang.org/x/tools/cmd/auth/gitauth@v0.32.0
go install golang.org/x/tools/cmd/go-contrib-init@v0.32.0
go install github.com/abice/go-enum@v0.6.1
go install github.com/google/go-licenses@v1.6.0
go install github.com/ramya-rao-a/go-outline@v0.0.0-20210608161538-9736a4bde949
go install github.com/acroca/go-symbols@v0.1.1
go install golang.org/dl/go1.22.11@v0.0.0-20250401154141-6c7fc191c4d8
go install github.com/stamblerre/gocode@v1.0.0
go install github.com/matm/gocov-html/cmd/gocov-html@v1.4.0
go install github.com/rogpeppe/godef@v1.1.2
go install golang.org/x/tools/cmd/godex@v0.32.0
go install golang.org/x/tools/cmd/godoc@v0.32.0
go install mvdan.cc/gofumpt@v0.8.0
go install golang.org/x/tools/cmd/goimports@v0.32.0
go install github.com/twpayne/go-jsonstruct/v3/cmd/gojsonstruct@v3.2.0
go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.2
go install github.com/segmentio/golines@v0.12.2
go install github.com/fatih/gomodifytags@v1.17.0
go install golang.org/x/tools/internal/modindex/gomodindex@v0.32.0
go install github.com/abenz1267/gomvp@v0.0.4
go install golang.org/x/tools/cmd/gomvpkg@v0.32.0
go install golang.org/x/tools/cmd/gonew@v0.32.0
go install golang.org/x/tools/go/packages/gopackages@v0.32.0
go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@v2.1.2
go install github.com/haya14busa/goplay/cmd/goplay@v1.0.0
go install golang.org/x/tools/gopls@v0.18.1
go install golang.org/x/tools/cmd/gorename@v0.1.0-deprecated
go install github.com/jstemmer/gotags@v1.4.1
go install github.com/rakyll/gotest@v0.0.6
go install github.com/cweill/gotests/gotests@v1.6.0
go install gotest.tools/gotestsum@v1.12.1
go install golang.org/x/tools/cmd/gotype@v0.32.0
go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
go install golang.org/x/tools/cmd/goyacc@v0.32.0
go install github.com/nao1215/gup@v0.27.8
go install golang.org/x/tools/cmd/guru@v0.1.1-deprecated
go install golang.org/x/tools/cmd/html2article@v0.32.0
go install golang.org/x/tools/go/analysis/passes/httpmux/cmd/httpmux@v0.32.0
go install golang.org/x/tools/go/analysis/passes/ifaceassert/cmd/ifaceassert@v0.32.0
go install github.com/koron/iferr@v0.0.0-20240122035601-9c3e2fbe4bd1
go install github.com/qeesung/image2ascii@v1.0.1
go install github.com/danielgatis/imgcat@v1.0.21
go install github.com/josharian/impl@v1.4.0
go install github.com/tmc/json-to-struct@v0.0.0-20230613234638-1f65fffbfdbb
go install github.com/birdayz/kaf/cmd/kaf@v0.2.13
go install github.com/evilmartians/lefthook@v1.11.11
go install loov.dev/lensm@v0.0.5
go install golang.org/x/tools/go/analysis/passes/lostcancel/cmd/lostcancel@v0.32.0
go install github.com/vektra/mockery/v2@v2.53.3
go install go.uber.org/mock/mockgen@v0.5.1
go install github.com/fatih/motion@v1.2.0
go install golang.org/x/tools/cmd/auth/netrcauth@v0.32.0
go install golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@v0.32.0
go install golang.org/x/tools/go/packages/internal/nodecount@v0.32.0
go install golang.org/x/tools/go/types/internal/play@v0.32.0
go install golang.org/x/tools/cmd/present@v0.32.0
go install golang.org/x/tools/cmd/present2md@v0.32.0
go install github.com/mgechev/revive@v1.9.0
go install github.com/kyoh86/richgo@v0.3.12
go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@v0.32.0
go install mvdan.cc/sh/v3/cmd/shfmt@v3.11.0
go install golang.org/x/tools/cmd/splitdwarf@v0.32.0
go install golang.org/x/tools/cmd/ssadump@v0.32.0
go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
go install golang.org/x/tools/cmd/stress@v0.32.0
go install golang.org/x/tools/cmd/stringer@v0.32.0
go install golang.org/x/tools/go/analysis/passes/stringintconv/cmd/stringintconv@v0.32.0
go install github.com/swaggo/swag/cmd/swag@v1.16.4
go install github.com/gcla/termshark/v2/cmd/termshark@v2.4.0
go install golang.org/x/tools/cmd/toolstash@v0.32.0
go install github.com/mfridman/tparse@v0.17.0
go install golang.org/x/tools/go/analysis/passes/unmarshal/cmd/unmarshal@v0.32.0
go install golang.org/x/tools/go/analysis/passes/unusedresult/cmd/unusedresult@v0.32.0
go install github.com/tsenart/vegeta@v12.7.0+incompatible
go install github.com/ysoftman/watchDust@v0.0.0-20250402122814-cc5716c4ee71
go install github.com/caddyserver/xcaddy/cmd/xcaddy@v0.4.4
