#!/bin/sh
code --install-extension DotJoshJohnson.xml
code --install-extension HookyQR.beautify
code --install-extension PeterJausovec.vscode-docker
code --install-extension abusaidm.html-snippets
code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.Bookmarks
code --install-extension dbaeumer.vscode-eslint
code --install-extension dcr30.lualinter
code --install-extension djabraham.vscode-yaml-validation
code --install-extension donjayamanne.jquerysnippets
code --install-extension eg2.tslint
code --install-extension fallenwood.vimL
code --install-extension haaaad.ansible
code --install-extension itryapitsin.Scala
code --install-extension johnpapa.Angular2
code --install-extension lukehoban.Go
code --install-extension magicstack.MagicPython
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension mitaki28.vscode-clang
code --install-extension mrmlnc.vscode-apache
code --install-extension ms-python.python
code --install-extension ms-vscode.Theme-MaterialKit
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.node-debug2
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension ravilang.ravi-debug
code --install-extension robertohuertasm.vscode-icons
code --install-extension shanoor.vscode-nginx
code --install-extension timonwong.ansible-autocomplete
code --install-extension vscodevim.vim
code --install-extension vsmobile.vscode-react-native
code --install-extension xabikos.JavaScriptSnippets
