#!/bin/bash
# auto generated by backupmysetting.sh
# install bun if not installed
command -v bun >/dev/null 2>&1 || curl -fsSL https://bun.com/install | bash
bun install -g @google/gemini-cli @openai/codex @vue/cli ccusage depcheck eslint firebase-tools knip node-gyp opencode-ai react-devtools tldr-lint typescript vite webpack webpack-cli
