#!/bin/sh
code --install-extension 13xforever.language-x86-64-assembly
code --install-extension abusaidm.html-snippets
code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.Bookmarks
code --install-extension azemoh.theme-onedark
code --install-extension bungcip.better-toml
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dcr30.lualinter
code --install-extension DevonDCarew.bazel-code
code --install-extension donjayamanne.jquerysnippets
code --install-extension DotJoshJohnson.xml
code --install-extension eg2.tslint
code --install-extension fallenwood.vimL
code --install-extension formulahendry.vscode-mysql
code --install-extension gaborv.flatbuffers
code --install-extension GitHub.vscode-pull-request-github
code --install-extension haaaad.ansible
code --install-extension HookyQR.beautify
code --install-extension itryapitsin.Scala
code --install-extension johnpapa.Angular2
code --install-extension magicstack.MagicPython
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension mechatroner.rainbow-csv
code --install-extension mitaki28.vscode-clang
code --install-extension mohsen1.prettify-json
code --install-extension mrmlnc.vscode-apache
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.node-debug2
code --install-extension ms-vscode.Theme-MaterialKit
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.vscode-react-native
code --install-extension octref.vetur
code --install-extension PeterJausovec.vscode-docker
code --install-extension ramyaraoa.show-offset
code --install-extension ravilang.ravi-debug
code --install-extension redhat.java
code --install-extension samuelcolvin.jinjahtml
code --install-extension shanoor.vscode-nginx
code --install-extension techer.open-in-browser
code --install-extension timonwong.ansible-autocomplete
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vitorsalgado.vscode-redis
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wholroyd.jinja
code --install-extension xabikos.JavaScriptSnippets
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension zxh404.vscode-proto3
