#!/bin/sh
code --install-extension 13xforever.language-x86-64-assembly
code --install-extension abusaidm.html-snippets
code --install-extension albymor.increment-selection
code --install-extension alefragnani.Bookmarks
code --install-extension atomiks.moonlight
code --install-extension bungcip.better-toml
code --install-extension cliffordfajardo.highlight-line-vscode
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cschlosser.doxdocgen
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dcortes92.FreeMarker
code --install-extension dcr30.lualinter
code --install-extension DevonDCarew.bazel-code
code --install-extension donjayamanne.jquerysnippets
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.tslint
code --install-extension esbenp.prettier-vscode
code --install-extension fallenwood.vimL
code --install-extension fivepointseven.vscode-theme-onedark-vivid
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.vscode-mysql
code --install-extension gaborv.flatbuffers
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension HookyQR.beautify
code --install-extension hoovercj.vscode-power-mode
code --install-extension itryapitsin.Scala
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension johnpapa.Angular2
code --install-extension josetr.cmake-language-support-vscode
code --install-extension kdl-org.kdl
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension mechatroner.rainbow-csv
code --install-extension mitaki28.vscode-clang
code --install-extension mongodb.mongodb-vscode
code --install-extension mrmlnc.vscode-apache
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.node-debug2
code --install-extension ms-vscode.Theme-MaterialKit
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.vscode-react-native
code --install-extension naco-siren.gradle-language
code --install-extension nobuhito.printcode
code --install-extension octref.vetur
code --install-extension ramyaraoa.show-offset
code --install-extension ravilang.ravi-debug
code --install-extension redhat.ansible
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension rust-lang.rust-analyzer
code --install-extension samuelcolvin.jinjahtml
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension sdras.night-owl
code --install-extension shanoor.vscode-nginx
code --install-extension sldobri.bunker
code --install-extension solnurkarim.html-to-css-autocompletion
code --install-extension sysoev.language-stylus
code --install-extension techer.open-in-browser
code --install-extension twxs.cmake
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vitorsalgado.vscode-redis
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vuetifyjs.vuetify-vscode
code --install-extension wholroyd.jinja
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension zamerick.vscode-caddyfile-syntax
code --install-extension zhuangtongfa.material-theme
code --install-extension zxh404.vscode-proto3
