#!/bin/bash
if [[ $(uname) != 'Darwin' ]]; then
    echo 'it is not mac system.'
    exit 0
fi

brew tap homebrew/cask-fonts
brew cask install font-hack-nerd-font java
brew install adns ansible aom apache-spark apr ascii asciidoc asciinema asciiquarium autoconf autoconf-archive automake bat bazel bdw-gc bmon boost boost-python brotli byobu c-ares caddy cairo calc ccache ccat ccze chrome-cli clang-format cmake cmatrix cmus confuse coreutils couchdb cowsay cronolog cscope ctags curl curl-openssl daemon daemonize dfu-programmer dive dkosctl docbook duti eigen erlang erlang@19 faad2 fcrackzip fd ffmpeg figlet fish flac flatbuffers fondu fontconfig fortune freetype frei0r fribidi fx fzf gcal gcc gd gdb gdbm gettext giflib git git-flow-avh glances glib glide gmp gnu-getopt gnu-sed gnu-tar gnupg gnutls go goaccess gperf gpgme gpm gradle graphite2 graphviz guetzli harfbuzz helm htop httpie httpstat hugo icu4c ifstat iftop ilmbase imagemagick isl jansson jemalloc jenkins jpeg jq jsoncpp kafkacat kubernetes-cli kubernetes-helm lame lazygit leptonica libao libarchive libass libassuan libbluray libcaca libcue libde265 libev libevent libffi libgcrypt libgpg-error libheif libidn libidn2 libksba libmaxminddb libmetalink libmpc libogg libomp libpng librdkafka libressl libsamplerate libsndfile libsoxr libssh2 libtasn1 libtermkey libtiff libtool libunistring libusb libusb-compat libvidstab libvorbis libvpx libxml2 libxslt libyaml little-cms2 llvm lolcat lsd lua lua@5.1 lynx lz4 lzlib lzo macvim mad maven memcache-top mercurial midnight-commander mono mp4v2 mpfr mplayer mps-youtube mpv mujs mutt mysql nasm ncurses neofetch nettle newt nghttp2 nginx ninja nmap node npth nspr nsq nss numpy nvm oniguruma openblas opencore-amr openexr openjdk openjdk@11 openjpeg openldap openssl openssl@1.1 opus p11-kit pcre pcre2 perl pidof pinentry pixman pkg-config poppler popt protobuf pv pyenv python python@2 python@3.8 readline redis rename ripgrep rtmpdump rubberband ruby rust s-lang sbt scala scons screenfetch screenresolution sdl2 shared-mime-info sift skaffold snappy socat source-highlight spdylay speex spidermonkey sqlite sshfs ssldump starship telnet tesseract thefuck theora thrift tig tmux tmux-xpanes toilet tokyo-cabinet tomcat tomcat-native tree uchardet unbound unibilium utf8proc vapoursynth vegeta vim vis vnstat w3m watch webp wget wrk wxmac x264 x265 xml2 xvid xz yajl yarn youtube-dl zimg zlib zsh
