#!/bin/bash

# go install 로 설치된 패키지 모두 업데이트
# gup update
#
# 에러 패키지 체크해서 있으면 제거
# gup check
# gup remove 패키지1, 패키지2...
#
# 패키지 목록 파악 설치 커맨드로 변경시
# gup list | awk '{sub(/@.*/, "@latest", $2); print "go install " $2}' | pbcopy
#
# install tools to $GOPATH/bin
go install github.com/air-verse/air@latest
go install github.com/ysoftman/aleng@latest
go install github.com/klauspost/asmfmt/cmd/asmfmt@latest
go install golang.org/x/tools/cmd/auth/authtest@latest
go install golang.org/x/tools/cmd/benchcmp@latest
go install golang.org/x/tools/cmd/bisect@latest
go install golang.org/x/tools/cmd/bundle@latest
go install golang.org/x/tools/cmd/callgraph@latest
go install golang.org/x/tools/cmd/compilebench@latest
go install github.com/maaslalani/confetty@latest
go install golang.org/x/tools/cmd/auth/cookieauth@latest
go install github.com/CondensedMilk7/countryfetch/cmd/countryfetch@latest
go install github.com/ysoftman/cutstring@latest
go install golang.org/x/tools/cmd/deadcode@latest
go install golang.org/x/tools/go/analysis/passes/defers/cmd/defers@latest
go install golang.org/x/tools/cmd/digraph@latest
go install github.com/go-delve/delve/cmd/dlv@latest
go install golang.org/x/tools/cmd/eg@latest
go install github.com/ysoftman/enchash@latest
go install github.com/kisielk/errcheck@latest
go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
go install golang.org/x/tools/cmd/file2fuzz@latest
go install github.com/davidrjenni/reftools/cmd/fillstruct@latest
go install github.com/davidrjenni/reftools/cmd/fillswitch@latest
go install golang.org/x/tools/go/analysis/passes/findcall/cmd/findcall@latest
go install github.com/ysoftman/findm@latest
go install golang.org/x/tools/cmd/fiximports@latest
go install github.com/pilu/fresh@latest
go install golang.org/x/tools/cmd/signature-fuzzer/fuzz-driver@latest
go install golang.org/x/tools/cmd/signature-fuzzer/fuzz-runner@latest
go install github.com/onsi/ginkgo/v2/ginkgo@latest
go install golang.org/x/tools/cmd/auth/gitauth@latest
go install golang.org/x/tools/cmd/go-contrib-init@latest
go install github.com/abice/go-enum@latest
go install github.com/google/go-licenses@latest
go install github.com/ramya-rao-a/go-outline@latest
go install github.com/acroca/go-symbols@latest
go install golang.org/dl/go1.22.11@latest
go install github.com/stamblerre/gocode@latest
go install github.com/matm/gocov-html/cmd/gocov-html@latest
go install github.com/rogpeppe/godef@latest
go install golang.org/x/tools/cmd/godex@latest
go install golang.org/x/tools/cmd/godoc@latest
go install mvdan.cc/gofumpt@latest
go install golang.org/x/tools/cmd/goimports@latest
go install github.com/twpayne/go-jsonstruct/v3/cmd/gojsonstruct@latest
go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
go install github.com/segmentio/golines@latest
go install github.com/fatih/gomodifytags@latest
go install golang.org/x/tools/internal/modindex/gomodindex@latest
go install github.com/abenz1267/gomvp@latest
go install golang.org/x/tools/cmd/gomvpkg@latest
go install golang.org/x/tools/cmd/gonew@latest
go install golang.org/x/tools/go/packages/gopackages@latest
go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
go install github.com/haya14busa/goplay/cmd/goplay@latest
go install golang.org/x/tools/gopls@latest
go install golang.org/x/tools/cmd/gorename@latest
go install github.com/securego/gosec/v2/cmd/gosec@latest
go install github.com/jstemmer/gotags@latest
go install github.com/rakyll/gotest@latest
go install github.com/cweill/gotests/gotests@latest
go install gotest.tools/gotestsum@latest
go install golang.org/x/tools/cmd/gotype@latest
go install golang.org/x/vuln/cmd/govulncheck@latest
go install golang.org/x/tools/cmd/goyacc@latest
go install github.com/nao1215/gup@latest
go install golang.org/x/tools/cmd/guru@latest
go install golang.org/x/tools/cmd/html2article@latest
go install golang.org/x/tools/go/analysis/passes/httpmux/cmd/httpmux@latest
go install golang.org/x/tools/go/analysis/passes/ifaceassert/cmd/ifaceassert@latest
go install github.com/koron/iferr@latest
go install github.com/qeesung/image2ascii@latest
go install github.com/danielgatis/imgcat@latest
go install github.com/josharian/impl@latest
go install github.com/tmc/json-to-struct@latest
go install github.com/birdayz/kaf/cmd/kaf@latest
go install github.com/kakao/kubectl-cilium@latest
go install github.com/evilmartians/lefthook@latest
go install loov.dev/lensm@latest
go install golang.org/x/tools/go/analysis/passes/lostcancel/cmd/lostcancel@latest
go install github.com/client9/misspell/cmd/misspell@latest
go install github.com/vektra/mockery/v3@latest
go install go.uber.org/mock/mockgen@latest
go install golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest
go install github.com/fatih/motion@latest
go install golang.org/x/tools/cmd/auth/netrcauth@latest
go install golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@latest
go install golang.org/x/tools/go/packages/internal/nodecount@latest
go install golang.org/x/tools/go/types/internal/play@latest
go install golang.org/x/tools/cmd/present@latest
go install golang.org/x/tools/cmd/present2md@latest
go install github.com/mgechev/revive@latest
go install github.com/kyoh86/richgo@latest
go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
go install mvdan.cc/sh/v3/cmd/shfmt@latest
go install golang.org/x/tools/cmd/splitdwarf@latest
go install golang.org/x/tools/cmd/ssadump@latest
go install honnef.co/go/tools/cmd/staticcheck@latest
go install golang.org/x/tools/cmd/stress@latest
go install golang.org/x/tools/cmd/stringer@latest
go install golang.org/x/tools/go/analysis/passes/stringintconv/cmd/stringintconv@latest
go install github.com/swaggo/swag/cmd/swag@latest
go install github.com/gcla/termshark/v2/cmd/termshark@latest
go install golang.org/x/tools/cmd/toolstash@latest
go install github.com/mfridman/tparse@latest
go install golang.org/x/tools/go/analysis/passes/unmarshal/cmd/unmarshal@latest
go install golang.org/x/tools/go/analysis/passes/unusedresult/cmd/unusedresult@latest
go install github.com/tsenart/vegeta@latest
go install github.com/ysoftman/watchDust@latest
go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
