version = 3
final_space = true

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[[blocks]]
type = 'prompt'
alignment = 'left'

# https://github.com/ysoftman/test_code/tree/master/rust/emoji/src
# cargo run main.rs 로 현재 사용중인 폰트 리스트 볼 수 있도록 했음.
# E0B0 ~ E0B3 : 4
#    
# E0B4 ~ E0C8 : 21
#                     
# E0CA ~ E0CA : 1
# 
# E0CC ~ E0D7 : 12
#            
# 또는 아이콘 참조: https://www.nerdfonts.com/cheat-sheet > nf-ple- 검색 > icon 복사

# https://ohmyposh.dev/docs/configuration/segment
[[blocks.segments]]
type = 'os'
style = 'diamond'
leading_diamond = ''
# template = '{{ .Icon }} {{ .HostName }}'
template = '{{ .Icon }} <b>{{ .UserName }}</b>'
foreground = '#00c983'
background = '#003543'

[[blocks.segments]]
type = 'kubectl'
style = 'powerline'
powerline_symbol = ''
template = '  {{.Context}}{{if .Namespace}}:{{.Namespace}}{{end}}'
foreground = '#FFD166'
background = "#433500"

[blocks.segments.properties]
[blocks.segments.properties.context_aliases]
'arn:aws:eks:eu-west-1:1234567890:cluster/posh' = 'posh'

[[blocks.segments]]
type = 'path'
style = 'powerline'
powerline_symbol = ''
template = ' <#74B9FF> </>{{ .Path }}'
foreground = '#74B9FF'
background = "#002B54"

[blocks.segments.properties]
folder_icon = ''
folder_separator_icon = '/'
home_icon = ''
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'powerline'
powerline_symbol = ''
# template = ' ({{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}) '
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#4A4A0D{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#4A4A0D{{ end }}",
  "{{ if gt .Ahead 0 }}#2A1054{{ end }}",
  "{{ if gt .Behind 0 }}#2A1054{{ end }}",
]
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFF192{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFF192{{ end }}",
  "{{ if gt .Ahead 0 }}#C77DFF{{ end }}",
  "{{ if gt .Behind 0 }}#C77DFF{{ end }}",
]
foreground = '#FF7F5F'
background = "#542A1A"

[blocks.segments.properties]
branch_icon = '  '
fetch_status = true
fetch_upstream_icon = true
fetch_stash_count = true
[blocks.segments.properties.mapped_branches]
"feat/*" = "🚀 "
"bug/*" = "🐛 "

[[blocks.segments]]
type = 'python'
style = 'powerline'
powerline_symbol = ''
template = ' 󰌠 {{ .Full }}'
foreground = '#C77DFF'
background = '#35004E'

[blocks.segments.properties]
display_mode = "files"

[[blocks.segments]]
type = 'node'
style = 'powerline'
powerline_symbol = ''
template = ' <#55EF72>󰎙</> {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
foreground = '#55EF72'
background = "#0D4E1A"

[[blocks.segments]]
type = "react"
style = "powerline"
powerline_symbol = ""
template = "  {{ .Full }}"
foreground = '#FF6B9D'
background = "#54002B"

[[blocks.segments]]
type = "bun"
style = 'powerline'
powerline_symbol = ''
template = " <#ffffff></> {{ .Full }}"
foreground = '#00E8A2'
background = "#004A3A"

[[blocks.segments]]
style = 'powerline'
type = 'go'
powerline_symbol = ''
template = '  {{ .Full }}'
foreground = '#9B7FFF'
background = '#1A0054'

[[blocks.segments]]
style = 'powerline'
type = 'rust'
powerline_symbol = ''
template = '  {{ .Full }}'
foreground = '#FFAA44'
background = '#543500'

[[blocks.segments]]
style = "powerline"
type = "helm"
powerline_symbol = ''
template = '  {{ .Version }}'
background = "#0D1A54"
foreground = "#6B8CFF"

[blocks.segments.properties]
display_mode = "files"

[[blocks.segments]]
type = 'time'
style = 'powerline'
powerline_symbol = ''
template = '  {{ .CurrentDate | date .Format }}'
foreground = '#FF5C6F'
background = "#540012"

[blocks.segments.properties]
# time_format = '3:04 PM'
time_format = "15:04:05"

[[blocks.segments]]
type = 'executiontime'
style = 'powerline'
powerline_symbol = ''
template = ' <#7BEF44>󰔟</> {{ .FormattedMs }}'
foreground = '#7BEF44'
background = "#1A5400"

[blocks.segments.properties]
always_enabled = true

[[blocks.segments]]
type = 'status'
style = 'diamond'
powerline_symbol = ''
trailing_diamond = ''
template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
background_templates = ['{{ if gt .Code 0 }}red{{ end }}']
foreground = '#FF6BD6'
background = "#540043"

[blocks.segments.properties]
always_enabled = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

# root user 일때
[[blocks.segments]]
type = 'root'
style = 'plain'
template = ' '
foreground = '#cd5e42'

[[blocks.segments]]
type = 'text'
style = 'plain'
template = ' <#45F1C2><b>⚡</b></><#26C6DA>❯</>'
foreground = '#CD4277'
